### ISSUE TITLE
how to track original docs update

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes-docs-zh#7]
it is really a big help to come up with such a repo.

I just want to know what if the original docs updates, what's the way to let us be aware and do the corresponding updates.

**Comment by iT2afL0rd** [comment]
Basically we translate for stable versions. And not follow the latest docs. Currently are working on release v1.1

**Comment by zhouhaibing089** [comment]
even for stable version, there would be fixes, how to track that, or we do it via manually check?

**Comment by iT2afL0rd** [comment]
Yes, this may be an issue, @hurf is working on a guideline for this task, I would suggest him take this into consideration. 

Thanks.

**Comment by zhouhaibing089** [comment]
@iT2afL0rd I think leveraging a bot to get notified whenever there is new commit into the given release(stable) branch is a good way.

**Comment by linfan** [comment]
maybe we do manually check currently, means the translated doc version should NOT earlier than the version of the first office release of that specified version (e.g. v1.2).
When newer changes come in, if anyone notice the change (or it must be COOL if there's a bot application), shout it out, and it would be nice to get fixed. Otherwise, we should follow it up in the next major release (e.g. v1.3).

**Comment by iT2afL0rd** [comment]
@zhouhaibing089 It is really cool to have a bot for fixes! But the key is how we process the fixes.

@linfan 's suggestion is acceptable, we can fix in next version, if next version is far away, we can fix it in current version.

**Comment by linfan** [comment]
Should we **make a rule** on it and close this issue.
Maybe in the README.md file?
